[package]
name = "venom"
version.workspace = true
edition.workspace = true
description = "Venom - GUI for cryptographic container management"

[[bin]]
name = "venom"
path = "src/main.rs"

[dependencies]
vnmcore = { path = "../vnmcore" }
eframe = { workspace = true }
egui = { workspace = true }
egui_extras = { workspace = true }
anyhow = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
rfd = { workspace = true }
